os: linux
dist: focal
language: go
go:
 - 1.15.x

env:
  # Using Go module (go 1.12 need this variable to be set to enable modules)
  # The variable should default to "on", in Go 1.14 release
  - GO111MODULE="on"

before_install:
  # MongoDb 4.2 docker container
  - docker container run -d -p 27017:27017 mongo:4.2 

services:
  - docker

script:
  - go get
  - ./test.sh
