language: go

go:
 - 1.11.4
 - 1.12

env:
  # Using Go module (go 1.12 need this variable to be set to enable modules)
  # The variable should default to "on", in Go 1.14 release
  - GO111MODULE="on"

script:
  - go get
  - ./test.sh
