language: go
os: linux
dist: bionic

jobs:
  include:
    - go: 1.12.17
      env: GO111MODULE=on
    - go: 1.14.x
  allow_failures:
    - go: 1.14.x

services:
  - mongodb

script:
  - go get
  - ./test.sh
